---
title: "IN2004B Generation of Value with Data Analytics"
subtitle: "Materials for Semester AD 2025"
author: 
  - name: Alan R. Vazquez
    orcid: 0000-0002-3658-0911
    affiliations:
      - name: Tecnologico de Monterrey
---

## Course topics

### Module 1

1.  Indicators ([slides](/Module1/Indicators.slides.html))
2.  Development and Visualization of Indicators ([slides](/Module1/BSC.slides.html))

### Module 2

1.  Introduction to Data Science ([slides](/Module2/IntrotoDataScience.slides.html)) 
2.  Decision trees for classification ([slides](/Module2/Classification.slides.html)) ([colab](https://drive.google.com/file/d/1iqtGTsLj0qL_zWwdkyrMsKltqOjvM496/view?usp=sharing))
3.  Ensamble methods ([slides](/Module2/EnsembleMethods.slides.html)) ([colab](https://drive.google.com/file/d/1HAn1pZL2oSJtISVfp2nrvNI8wYzwtAV9/view?usp=sharing))
4.  *K*-nearest neighbours ([slides](/Module2/KNearestNeighbours.slides.html)) ([colab](https://drive.google.com/file/d/1ItiD4OZrk46WSBHhh_d0va7F-5lY6f25/view?usp=sharing))

### Module 3

1.  Predictive Models ([slides](/Module3/PredictiveModels.slides.html)) ([colab](https://drive.google.com/file/d/12x5bgN_Tt5DAO38DGbeqhPM36gEETCqb/view?usp=sharing))
2.  Autocorrelation Models ([slides](/Module3/Autocorrelation.slides.html)) ([colab](https://drive.google.com/file/d/1G2EzXu1iOV5UpP_qzU1nUknGJ5FPY0lg/view?usp=sharing))
3.  Ensamble Methods for Time Series

### Module 4

1.  Clustering Methods ([slides](/Module4/Clustering.slides.html)) ([colab](https://colab.research.google.com/drive/1sL5LeIXI9YqYmebxWpF3sqPA92IxftYX?usp=sharing))
2.  Principal Component Analysis ([slides](/Module4/PCA.slides.html))

## About the author

Alan R. Vazquez ([website](https://alanrvazquez.netlify.app/)) is a Research Professor at the Department of Industrial Engineering at Tecnologico de Monterrey, Monterrey campus.

### License
